[package]
name = "temp-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
nvml-wrapper = "0.11.0"
clap = { version = "4.5.45", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
